In [21]:
import numpy as np

# الف

In [22]:
e_1 = np.array([
    1,-1,1,
    -1,1,-1,
    -1,1,-1,
    1,-1,1,
])

e_2 = np.array([
    1,-1,1,
    -1,1,-1,
    -1,1,-1,
    -1,1,-1,
])

e_3 = np.array([
    -1,1,-1,
    1,-1,1,
    1,1,1,
    1,-1,1,
])

e_4 = np.array([
    -1,1,1,
    1,-1,-1,
    1,-1,-1,
    -1,1,1,
])

In [23]:
e = np.zeros((4, 12))

In [24]:
e[0,:] =e_1
e[1,:] =e_2
e[2,:] =e_3
e[3,:] =e_4

In [25]:
b1= e_1.shape[0]/2
b2= e_1.shape[0]/2
b3= e_1.shape[0]/2

In [26]:
w = np.zeros((12, 4))
for i in range(e.shape[0]):
    for j in range(e.shape[1]):
        w[j,i] = e[i,j]/2

In [32]:
for i in range(4):
    for j in range(4):
        if j!=i :
            y_in = (e_1.shape[0]/2) + np.inner(e[i,:] ,w[:,j])
            print('hamming distance between picture {} and {} is : {} '.format(i,j,y_in) )

hamming distance between picture 0 and 1 is : 9.0 
hamming distance between picture 0 and 2 is : 4.0 
hamming distance between picture 0 and 3 is : 4.0 
hamming distance between picture 1 and 0 is : 9.0 
hamming distance between picture 1 and 2 is : 1.0 
hamming distance between picture 1 and 3 is : 5.0 
hamming distance between picture 2 and 0 is : 4.0 
hamming distance between picture 2 and 1 is : 1.0 
hamming distance between picture 2 and 3 is : 6.0 
hamming distance between picture 3 and 0 is : 4.0 
hamming distance between picture 3 and 1 is : 5.0 
hamming distance between picture 3 and 2 is : 6.0 


# ب

In [33]:
e = np.zeros((4, 12))
e[0,:] =e_1
e[1,:] =e_2
e[2,:] =e_3
e[3,:] =e_4
w = np.zeros((12, 4))
for i in range(e.shape[0]):
    for j in range(e.shape[1]):
        w[j,i] = e[i,j]/2
print("weight matrix : ", w)
bias = e_1.shape[0]/2
print("bias : ", bias)

weight matrix :  [[ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5  0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]
 [ 0.5  0.5  0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5  0.5]]
bias :  6.0


# پ

In [34]:
input_T = np.array([
    1,1,1,
    -1,1,-1,
    -1,1,-1,
    -1,1,-1,
])

In [37]:
y_in = []
for i in range(4):
    y_in = (e_1.shape[0]/2) + np.inner(input_T ,w[:,i])
    print('hamming distance between picture input_T and {} is : {} '.format(i,y_in) )

hamming distance between picture input_T and 0 is : 8.0 
hamming distance between picture input_T and 1 is : 11.0 
hamming distance between picture input_T and 2 is : 2.0 
hamming distance between picture input_T and 3 is : 6.0 
